#!/bin/bash

# Update The System
apt-get update -y
apt-get upgrade -y

# Create directories
mkdir ~/workspace
mkdir ~/workspace/MRifat
mkdir ~/workspace/contributions
mkdir ~/services

# Install basic applications
apt-get -y --force-yes vim git htop postgresql libpq-dev build-essential bison openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libxml2-dev libxslt-dev autoconf libc6-dev nodejs

# Clone necessary repos
cd ~/workspace/MRifat
git clone https://github.com/MRifat/randomness.git
git clone https://github.com/MRifat/dotfiles.git

# Setup Vim
mkdir ~/.vim/colors
cp dotfiles/vimrc ~/.vimrc
cp dotfiles/twilight.vim ~/.vim/colors/.
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

# Clone contributions
cd workspace/contributions
git clone https://github.com/railsgirls/railsgirls.git
git clone https://github.com/MRifat/railsgirls.github.com.git
git clone https://github.com/MRifat/oath.git

# Install Redis
cd services
git clone https://github.com/antirez/redis.git
cd redis
make install
cd utils
./install_server.sh
cd

# Configure PostgreSQL
su - postgres
create role $1 with createdb login password $2
# psql -c "CREATE USER $1 WITH PASSWORD '$2';"

# Setup rbenv
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
git clone https://github.com/sstephenson/rbenv-gem-rehash.git ~/.rbenv/plugins/rbenv-gem-rehash
git clone https://github.com/maljub01/rbenv-bundle-exec.git ~/.rbenv/plugins/rbenv-bundle-exec

# Install Rubies
for version in `cat ~/workspace/randomness/ruby-versions`; do rbenv install $version; done

# We're Done
echo ""
echo "==================="
echo "====We're Done!===="
echo "==================="
echo ""
echo "You might wanna update this script soon!"
